### ISSUE TITLE
Imagem do README quebrada

### ISSUE THREAD

**Issue by mayraamaral** [josemalcher/Curso-Web-Moderno-com-JavaScript-2019-COMPLETO-Projetos#1]
Olá José! Tudo bem? 

Encontrei teu perfil por acaso no Github, estou fazendo o curso de JS da Rocketseat e achei teu repositório com anotações do curso, e então vi esse daqui e resolvi conferir, aqui o link da imagem que você linka no README https://github.com/josemalcher/Curso-Web-Moderno-com-JavaScript-2019-COMPLETO-Projetos/raw/master/img%5C01-01-introducao.PNG ela não está aparecendo lá.

Além de falar disso, gostaria de dizer que você é uma inspiração para mim (sou dev iniciante) e ver todo o seu progresso é muito encorajador. 
Cordialmente,
Mayra Amaral.

**Comment by josemalcher** [comment]
Olá @mayraamaral 
Obrigado por me avisar! Já corrigi!
Fico feliz por você me encontrar aqui e por prestigiar meus resumos de estudos. Uso eles para consultar sempre que precisar tirar alguma dúvida, etc!
Bom ver Dev. iniciante já usando o Github, é importante para ir fazendo um portfólio e interagir!
Precisando de alguma ajuda, estamos por aqui!

Abraços!
